// Code generated by go-bindata.
// sources:
// 000001_init.down.sql
// 000001_init.up.sql
// 000002_log.down.sql
// 000002_log.up.sql
// DO NOT EDIT!

package migrations

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var __000001_initDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x72\x09\xf2\x0f\x50\x08\x71\x74\xf2\x71\x55\xf0\x74\x53\x70\x8d\xf0\x0c\x0e\x09\x56\xc8\x4d\x2d\x29\xca\x4c\xb6\xe6\xc2\x2a\x99\x5c\x82\x4b\x22\x3f\x2f\x2d\x33\xdd\x9a\x0b\x10\x00\x00\xff\xff\xcc\xc4\x2f\x49\x53\x00\x00\x00")

func _000001_initDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_initDownSql,
		"000001_init.down.sql",
	)
}

func _000001_initDownSql() (*asset, error) {
	bytes, err := _000001_initDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init.down.sql", size: 83, mode: os.FileMode(420), modTime: time.Unix(1597495004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __000001_initUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x9c\x90\xcf\x4e\xf3\x30\x10\xc4\xef\x7e\x8a\x39\x26\x52\xdf\xe0\x3b\xf9\x73\x37\x95\x85\xe3\x84\xcd\x5a\xa2\xa7\x2a\x6a\x0d\xb2\x44\xd2\x0a\x0c\xe2\xf1\x51\x12\xfe\x48\x50\x51\x81\x8f\xb3\xbb\xe3\xdf\x8c\x61\xd2\x42\x10\xfd\xdf\x91\xb2\x15\x7c\x23\xa0\x1b\xdb\x49\x87\x21\xe6\x87\xb4\x57\x85\x02\x80\x74\x80\xf5\x42\x1b\xe2\x79\xc5\x07\xe7\xd0\xb2\xad\x35\x6f\x71\x45\xdb\xd5\xbc\x34\xf6\x43\x44\x8e\x2f\x59\x95\xff\x94\xfa\xc1\x7a\x9f\x7f\x63\x9b\xd3\x10\x1f\x73\x3f\x9c\xb0\xd6\x42\x62\x6b\xc2\x9a\x2a\x1d\x9c\xc0\x04\x66\xf2\xb2\x9b\xc4\x4e\x74\xdd\x2e\x17\x0b\xfa\xee\x8c\xfb\x32\x7f\xee\xef\x9f\x22\xd2\x98\xbf\xe8\x55\xc3\x64\x37\x7e\xfa\xba\xf8\xf0\x28\xc1\x54\x11\x93\x37\xf4\x5e\x4a\x91\x0e\xe5\xc5\x8c\xc7\xf1\x36\xdd\xe1\x2d\xe8\x25\xa2\xe3\x29\xcf\xcd\x7d\x07\x3d\x27\x07\x6f\xaf\x03\x7d\x22\xae\xa6\xfb\x72\x1e\x4d\xaf\xf1\x30\x8d\xaf\x9c\x35\x02\xa6\xd6\x69\x43\x7f\xcb\xf7\x1a\x00\x00\xff\xff\x10\x01\xe1\xc0\x1e\x02\x00\x00")

func _000001_initUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000001_initUpSql,
		"000001_init.up.sql",
	)
}

func _000001_initUpSql() (*asset, error) {
	bytes, err := _000001_initUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000001_init.up.sql", size: 542, mode: os.FileMode(420), modTime: time.Unix(1597495004, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __000002_logDownSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x90\xc1\x6a\xc3\x30\x10\x44\xef\xfa\x8a\x39\xda\xe0\x3f\xc8\x49\xb5\x57\x41\x54\x96\xcc\x6a\x0d\xcd\x29\x04\xdb\x14\x41\xdc\x96\x56\xed\xf7\x17\xdb\x69\x0d\xa5\xe4\x3a\x33\x3b\x6f\x99\x9a\x49\x0b\x41\xf4\x83\x23\x65\x0d\x7c\x10\xd0\x93\x8d\x12\x31\x64\x55\x28\x00\x48\x23\xac\x17\x3a\x12\xaf\xb6\xef\x9d\x43\xc7\xb6\xd5\x7c\xc2\x23\x9d\xaa\x35\x94\xd3\x3c\x7d\xe4\xcb\xfc\x86\x46\x0b\x89\x6d\x09\x0d\x19\xdd\x3b\x41\xdd\x33\x93\x97\xf3\x22\x46\xd1\x6d\xb7\x5d\xcc\x53\x7e\x4f\xc3\xf9\x9f\xf6\xcd\xff\xba\x5c\x3f\x27\xa4\x97\xfc\x47\x37\x81\xc9\x1e\xfd\x82\x2e\x7e\x3b\x4a\x30\x19\x62\xf2\x35\xc5\x5b\x73\x91\xc6\x52\x95\x07\xa5\xac\x8f\xc4\xb2\x50\x02\x86\x5c\xa4\xb1\xda\xd9\xd5\x86\xa9\xf6\xff\x4b\x44\x72\x54\xdf\x88\xf7\x92\x30\x1c\x5a\x5c\x5f\x9f\x0f\x4a\x35\x1c\xba\x6d\x45\x58\xf3\xb3\xe0\x6a\x7d\x07\x00\x00\xff\xff\xc8\x17\x88\xf2\x62\x01\x00\x00")

func _000002_logDownSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_logDownSql,
		"000002_log.down.sql",
	)
}

func _000002_logDownSql() (*asset, error) {
	bytes, err := _000002_logDownSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_log.down.sql", size: 354, mode: os.FileMode(420), modTime: time.Unix(1598160411, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var __000002_logUpSql = []byte("\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x7c\x90\x41\x6a\xc3\x30\x10\x45\xf7\x3a\xc5\x2c\x6d\xf0\x0d\xb2\x52\x9d\xef\x20\x2a\x4b\xee\x68\x04\xcd\x2a\x84\xd8\x14\x41\xdc\x96\x56\xed\xf9\x8b\xad\x10\x43\x29\x5d\x6a\xe6\x0d\xff\x7d\xb5\x0c\x2d\x20\xd1\x0f\x16\xca\x74\xe4\xbc\x10\x9e\x4d\x90\x40\xd7\xb7\x17\x55\x29\x22\xa2\x34\x92\x71\x82\x03\x78\xdd\xbb\x68\x2d\x0d\x6c\x7a\xcd\x47\x7a\xc4\xb1\x59\xa1\x79\xca\x1f\xe9\x72\xfa\x83\x2d\xfb\xef\xf3\xf5\x6b\xa2\xf4\x9a\x7f\xcd\x73\x9a\xa7\xcf\x7c\x9e\xdf\x69\xaf\x05\x62\x7a\xd0\x1e\x9d\x8e\x56\xa8\x8d\xcc\x70\x72\x5a\x86\x41\x74\x3f\x94\x8b\xce\x33\xcc\xc1\x2d\xd1\xd5\x3d\xb5\x26\x46\x07\x86\x6b\x11\x6e\x2e\x55\x1a\xeb\x72\x11\x9d\x79\x8a\xd8\xe0\xe6\x1e\x5a\xab\x7a\xa7\x94\x71\x01\x2c\x8b\xb8\x5f\x6a\x57\x69\x6c\xb6\x3e\x4d\x51\x6f\x36\xd3\x9a\x02\x2c\xda\x5b\x8b\xff\x48\xea\xd8\xf7\x74\xc9\x3b\xa5\xf6\xec\x87\xf2\xcf\xeb\xfb\x27\x00\x00\xff\xff\x47\x6b\xd9\x83\x79\x01\x00\x00")

func _000002_logUpSqlBytes() ([]byte, error) {
	return bindataRead(
		__000002_logUpSql,
		"000002_log.up.sql",
	)
}

func _000002_logUpSql() (*asset, error) {
	bytes, err := _000002_logUpSqlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "000002_log.up.sql", size: 377, mode: os.FileMode(420), modTime: time.Unix(1598160355, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"000001_init.down.sql": _000001_initDownSql,
	"000001_init.up.sql": _000001_initUpSql,
	"000002_log.down.sql": _000002_logDownSql,
	"000002_log.up.sql": _000002_logUpSql,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"000001_init.down.sql": &bintree{_000001_initDownSql, map[string]*bintree{}},
	"000001_init.up.sql": &bintree{_000001_initUpSql, map[string]*bintree{}},
	"000002_log.down.sql": &bintree{_000002_logDownSql, map[string]*bintree{}},
	"000002_log.up.sql": &bintree{_000002_logUpSql, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

