name: CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.2'

    - name: lint
      run: make lint

  unit-tests:
    name: unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.2'

    - name: unit tests
      run: make test

  integration-tests:
    name: integration tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.2'

    - name: set env for go
      run: |
        echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

    - name: install
      run: make install

    - name: install bats
      run: sudo npm install -g bats

    - name: integration tests
      run: make integration-tests
