name: main
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: build, lint & test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: '1.15.0'

    - name: install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint

    - name: run vet & lint
      run: |
        go vet .
        golint -set_exit_status . cmd config internal/...

    - name: run tests
      run: go test ./...

    - name: build
      env:
        GOOS: linux
        GOARCH: amd64
      run: make ct
